### PR TITLE
Fix for Website is not Fully Responsive

### PR DESCRIPTION
**Pull request by Raamprathap**
I have aligned all the elements on every page to look good in 360x640 for phones and 768x1024 for tablets. This is a URL to verify  the changes I have made https://raamprathap.github.io/TN-Tourism.github.io/

### CODE REVIEW

**Comment by Raamprathap** [comment]
@SaranDharshanSP

**Comment by SaranDharshanSP** [comment]
Do mention which issue you solved.
and also once pull the repo as there are conflict changes.

**Comment by Raamprathap** [comment]
I have resolved the conflicts
and the issue is: Website is Not Fully Responsive on Mobile Devices #1 
@SaranDharshanSP

**Comment by Raamprathap** [comment]
@SaranDharshanSP

**Review by SaranDharshanSP — APPROVED** [review]
Looks good to me but it seems to have merge conflicts. Have a look into it to be merged.

**Comment by Raamprathap** [comment]
@SaranDharshanSP I have resolved all conflicts

**Comment by SaranDharshanSP** [comment]
LGTM

**Comment by Raamprathap** [comment]
The bounty for this issue is mentioned as100
@SaranDharshanSP

**Comment by Raamprathap** [comment]
@SaranDharshanSP

**Pull request merged**
