### PR TITLE
updated the image transition

### LINKED ISSUE #3: Image Click Transition Error on Food Page
### Description
Clicking on images in the food page causes an unexpected error or glitch during the transition effect. The transition either doesn't complete properly or breaks the layout.

### Steps to Reproduce
1. Navigate to the food page.
2. Click on any image to trigger the transition effect.
3. Observe the error or unexpected behavior.

### Expected Behavior
The image should transition smoothly without any errors or layout issues.

### Current Behavior
The transition effect either breaks the layout or causes a glitch in the user interface.

### Severity
**Medium**  
*Impacts user experience but does not block functionality.*

### Suggested Fix
- Review and debug the CSS/JavaScript responsible for the transition.
- Ensure compatibility across all browsers and devices.
- Test for any conflicts with other components or scripts on the page.

### PR DESCRIPTION
**Pull request by priyansh-narang2308**
" Resolves #3 "
Fixed image sequencing to ensure proper circular navigation
Did  z-index to prevent image clashing behind center image
 Optimized image visibility states  TO left, center, right positions
Verified smooth transitions when clicking left/right images
 Confirmed no image overlapping occurs behind center image
 Tested  rotation through all 5 images
image

### CODE REVIEW

**Comment by SaranDharshanSP** [comment]
Please do write : " Resolves #3 "

**Review by SaranDharshanSP — CHANGES_REQUESTED** [review]
Looks good. Please do deploy it in your branch so that i could verify and merge it !! @priyansh-narang2308

**Comment by priyansh-narang2308** [comment]
Yeah 
Updated the description with Resolves #3 
and even deployed to my branch named update-image-transition
I deployed it using the GitHub pages 
The deployed link is https://priyansh-narang2308.github.io/TN-Tourism.github.io/

**Comment by SaranDharshanSP** [comment]
> Yeah Updated the description with Resolves #3 and even deployed to my branch named update-image-transition I deployed it using the GitHub pages The deployed link is https://priyansh-narang2308.github.io/TN-Tourism.github.io/

Good Job !!

**Comment by priyansh-narang2308** [comment]
So will my bounties be updated?

**Comment by SaranDharshanSP** [comment]
> So will my bounties be updated?

soon it will be updated.

**Review by SaranDharshanSP — APPROVED** [review]
GTG

**Pull request merged**
